version: '3.7'
services:
  gbapp-mysql:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gbapp
      #      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin
    ports:
      - "3307:3306"
#  gbapp-liquibase:
#    container_name: gbapp-liquibase
#    image: liquibase/liquibase
#    links:
#      - gbapp-mysql
#    command: --driver=com.mysql.jdbc.Driver --changeLogFile=/db/changelog/dbchangelog-prod.xml --url=jdbc:mysql://gbapp-mysql:3306/gbapp?autoReconnect=true&useSSL=false --username=root --password=admin update
  gbapp:
    build: .
    container_name: gbapp
    ports:
      - "8080:8080"
    depends_on:
      - gbapp-mysql

    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DATABASE_HOST=gbapp-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=admin
      - DATABASE_NAME=gbapp
      - DATABASE_PORT=3306
#      - spring.liquibase.url=jdbc:mysql://localhost:3306/gbapp?autoReconnect=true&useSSL=false
#      - spring.liquibase.user=root
#      - spring.liquibase.password=admin
