--liquibase formatted sql
--changeset kris:1
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (1, '00:00', '00:30', 'night');
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (2, '00:30', '01:00', 'night');
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (3, '01:00', '01:30', 'night');
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (4, '01:30', '02:00', 'night');
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (5, '02:00', '02:30', 'night');
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (6, '02:30', '03:00', 'night');
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (7, '03:00', '03:30', 'night');
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (8, '03:30', '04:00', 'night');
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (9, '04:00', '04:30', 'night');
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (10,'04:30', '05:00', 'night');
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (11, '05:00','05:30', 'night');
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (12, '05:30','06:00', 'night');
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (13, '06:00','06:30', 'morning');
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (14, '06:30','07:00', 'morning');
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (15, '07:00', '07:30', 'morning');
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (16, '07:30', '08:00', 'morning');
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (17, '08:00', '08:30', 'morning');
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (18, '08:30', '09:00', 'morning');
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (19, '09:00', '09:30', 'morning');
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (20, '09:30', '10:00', 'morning');
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (21, '10:00', '10:30', 'morning');
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (22, '10:30', '11:00', 'morning');
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (23, '11:00', '11:30', 'morning');
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (24, '11:30', '12:00', 'morning');
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (25, '12:00', '12:30', 'afternoon');
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (26, '12:30', '13:00', 'afternoon');
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (27, '13:00', '13:30', 'afternoon');
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (28, '13:30', '14:00', 'afternoon');
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (29, '14:00', '14:30', 'afternoon');
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (30, '14:30', '15:00', 'afternoon');
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (31, '15:00', '15:30', 'afternoon');
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (32, '15:30', '16:00', 'afternoon');
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (33, '16:00', '16:30', 'afternoon');
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (34, '16:30', '17:00', 'afternoon');
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (35, '17:00', '17:30', 'evening');
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (36, '17:30', '18:00', 'evening');
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (37, '18:00', '18:30', 'evening');
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (38, '18:30', '19:00', 'evening');
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (39, '19:00', '19:30', 'evening');
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (40, '19:30', '20:00', 'evening');
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (41, '20:00', '20:30', 'evening');
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (42, '20:30', '21:00', 'evening');
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (43, '21:00', '21:30', 'evening');
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (44, '21:30', '22:00', 'evening');
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (45, '22:00', '22:30', 'night');
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (46, '22:30', '23:00', 'night');
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (47, '23:00', '23:30', 'night');
INSERT INTO timeslot(id, start_time, end_time, description) VALUES (48, '23:30', '00:00', 'night');